module FloodLight {
    @topic
    struct LDUpdate {
        long src;
        octet srcPort;
        long dst;
        octet dstPort;
        octet srcType;
        long latency;
        octet type;
        octet operation;
    };
};